version: "3.4"

services:

  api:
    build:
      dockerfile: Dockerfile
      context: ./api
      target: development
    command: npm run start:dev
    volumes:
      - ./api:/transcendence_app/api/src/app
      - /transcendence_app/api/src/app/node_modules
    # or npm run start:debug --> vscode debugger
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - 3000:3000

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
      target: development
    command: npm run start
    volumes:
      - ./frontend:/transcendence_app/frontend/src/app
      - /transcendence_app/frontend/src/app/node_modules
    ports:
      - 4200:4200
    # maybe user networks instead?
    links:
      - api
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 35000:5432

  postgres_admin:
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80
